In [1]:
# 数据分类
# 1 定类（类别）：根据事物离散、无差别属性进行分类。类别间是无差距的，例如性别、民族
# 2 定序（顺序）：可以界定数据的大小，但不能测定差值。有差距，但无法衡量。例如收入的低、中、高
# 3 定距（间距）：可以界定数据的大小的同时，可测定差值，但无绝对零点。乘除法无意义。例如：温度
# 4 定比（比率）：可以界定数据大小，可测定差值，有绝对零点。例如：身高、体重、长度、体积等

In [2]:
# 单属性分析
# 异常值分析：
    # 离散异常值（离散属性范围外的值，例如空值）
    # 连续异常值（用四分位数来界定，k取1.5-3之间的数）
    # 知识异常值（在限定知识与常识范围外的值，例如身高10米）
# 对比分析：绝对数与相对数、时间、空间、理论纬度比较
    # 绝对数比较：比较收入、身高、成绩
    # 相对数比较：
    # 结构相对数（部分与整体进行相比，例如合格率、通过率）
    # 比例相对数（总体内用不同部分的数值进行比较，例如农业、重工业和服务业之间的比较）
    # 比较相对数（同一时空下的相似的指标进行对比，例如不同时期下的同样商品的价格比较，不同电商互联网的待遇水平）
    # 动态相对数（具有时间概念，例如：速度、用户增速）、
    # 强度相对数（性质不同但有相互联系的属性进行联合，例如人均、粮食的亩产、密度等）
    # 怎么比？
    # 时间纬度：现在和过去比、过去和以前比等，由此可以推断出未来的走势
    # 同比（是和去年同期进行比较，例如今年6月份的数据就要和去年6月份的数据进行比较），环比（比较的是当前时期的前一个月，例如今年6月份的数据就要和今年5月份的数据进行比较）
    # 空间纬度：现实方位上的空间，例如：不同的城市、不同的国家、地区等。也可指逻辑上的空间，例如：一家公司的不同部门、或不同公司间比较
    # 经验与计划：经验，例如历史上失业率达到多少，就要开始发生暴乱。 计划，工作的实时进度与排期进行比较
# 结构分析：各组成部分的分布与规律（等同于比例相对数的比较）
    # 动态结构分析：以时间为轴分析结构变化的趋势，比如已知十五期间三大产业的占比，对于十一五期间我国三大产业的结构如何变化，就可以反应我国性质上的发展方向。
    # 静态结构分析：直接分析总体的组成，例如十五期间我国三大产业之间的比例
# 分布分析：数据分布频率的显式分布
    # 直接获得概率分布：将得到的一些数直接进行排列或者对于离散的数值，将离散的值挑出来，排列一下就可以得到其分布
    # 是不是正太分布：若是正太分布就可以用已有的性质对其进行操作。偏态值比较大，或者峰态值（若峰态值为3，则小于1大于5的），不是正太分布
    # 极大似然：极大相似的样子，如果给出一串数字且符合正太分布，就一定有可以确定一个均值一个方差，是该均值和该方差确定的正太分布下的值的和或积取对数。

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./data/HR.csv')

In [5]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14997                    280                   4              0     1   
14998                    158                   3              0     1   
14999                    158                   3              0     1   
15000                    158                   3              0     1   
15001                    158                   2              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14997                      0    support     low  
14998                      0    support     low  
14999                      0    support     low  
15000                      0       sale     low  
15001                      0       sale     nme  

[15002 rows x 10 columns]

In [6]:
# 异常值分析
sl_s = df['satisfaction_level']
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [7]:
# 查看异常值
sl_s[sl_s.isnull()]

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [9]:
# 查看satisfaction_level中异常值，在总数据中的具体情况
df[df['satisfaction_level'].isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [14]:
# 填充异常值
# sl_s.fillna()

# 删除异常值
sl_s = sl_s.dropna()

In [11]:
sl_s

0        0.38
1        0.80
2        0.11
3        0.72
4        0.37
         ... 
14995    0.37
14996    0.37
14997    0.11
14998    0.37
15001    0.70
Name: satisfaction_level, Length: 15000, dtype: float64

In [15]:
# 获取均值
sl_s.mean()

0.6128393333333343

In [16]:
# 标准差
sl_s.std()

0.24862338135945417

In [17]:
# 最大值
sl_s.max()

1.0

In [18]:
# 最小值
sl_s.min()

0.09

In [19]:
# 中位数
sl_s.median()

0.64

In [20]:
# 下四分位数
sl_s.quantile(q=0.25)

0.44

In [21]:
# 上四分位数
sl_s.quantile(q=0.75)

0.82

In [22]:
# 偏度
sl_s.skew()

-0.47643761717258093

In [23]:
# 峰度
sl_s.kurt()

-0.6706959323886252

### 获取离散化分布

In [24]:
np.histogram(sl_s.values, bins=np.arange(0.0, 1.1, 0.1))

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

## 最近评价分析

In [25]:
le_s = df['last_evaluation']

In [26]:
le_s

0             0.53
1             0.86
2             0.88
3             0.87
4             0.52
           ...    
14997         0.96
14998         0.52
14999         0.52
15000    999999.00
15001         0.40
Name: last_evaluation, Length: 15002, dtype: float64

In [27]:
# 查看是否有空值
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

In [28]:
# 均值
le_s.mean()

67.37373216904412

In [29]:
# 标准差
le_s.std()

8164.407523745649

In [30]:
# 中位数
le_s.median()

0.72

In [31]:
# 最大值
le_s.max()

999999.0

In [32]:
# 最小值
le_s.min()

0.36

In [33]:
# 偏度
le_s.skew()

122.48265175204614

In [34]:
# 峰度
le_s.kurt()

15001.999986807796

In [35]:
# 查看大于1的值
le_s[le_s > 1]

15000    999999.0
Name: last_evaluation, dtype: float64

In [36]:
# 剔除异常值
le_s[le_s<=1]

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

### 利用四分位数提取有效数据

In [37]:
# 下四分位数
q_low = le_s.quantile(q = 0.25)

In [38]:
# 上四分位数
q_high = le_s.quantile(q = 0.75)

In [39]:
# 四分位间距
q_interval = q_high - q_low

In [41]:
k = 1.5

In [42]:
# 有效值小于上四分位数加上k倍的四分位间距，大于下四分位数-k倍的四分位间距
le_s = le_s[le_s < q_high + k*q_interval][le_s > q_low - k*q_interval]

In [43]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [44]:
len(le_s)

15001

In [48]:
# 获取离散值
np.histogram(le_s.values, bins=np.arange(0.0, 1.1, 0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [50]:
# 去除异常值后，重新计算均值、标准差、中位数等
le_s.mean()
le_s.std()
le_s.median()
le_s.max()
le_s.skew()
le_s.kurt()

-1.2390454655108427

### number_project 分析

In [51]:
np_s = df["number_project"]

In [53]:
# 查看异常值
np_s[np_s.isnull()]

Series([], Name: number_project, dtype: int64)

In [54]:
# 均值
np_s.mean()

3.8026929742700974

In [55]:
np_s.std()

1.2327327792005955

In [56]:
np_s.median()

4.0

In [57]:
np_s.max()

7

In [58]:
np_s.min()

2

In [59]:
# 偏度
np_s.skew()

0.3377744235231047

In [60]:
# 峰度
np_s.kurt()

-0.49580962709450604

In [61]:
# 由于数据较为规律，可以直接查看每个数据出现的次数
np_s.value_counts()

4    4365
3    4055
5    2761
2    2391
6    1174
7     256
Name: number_project, dtype: int64

In [63]:
# 查看比率，并排序
np_s.value_counts(normalize=True).sort_index()

2    0.159379
3    0.270297
4    0.290961
5    0.184042
6    0.078256
7    0.017064
Name: number_project, dtype: float64

### average_monthly_hours 分析

In [64]:
amh_s = df['average_monthly_hours']

In [65]:
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

In [66]:
amh_s.mean()

201.0417277696307

In [67]:
amh_s.std()

49.94181527437911

In [68]:
amh_s.max()

310

In [69]:
amh_s.min()

96

In [70]:
# 偏度
amh_s.skew()

0.05322458779916304

In [71]:
# 峰度
amh_s.kurt()

-1.1350158577565719

In [72]:
# 利用四分位数取出正常值
amh_s = amh_s[amh_s<amh_s.quantile(0.75)+1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25)-1.5*(amh_s.quantile(0.75)-amh_s.quantile(0.25))]

In [73]:
amh_s

0        157
1        262
2        272
3        223
4        159
        ... 
14997    280
14998    158
14999    158
15000    158
15001    158
Name: average_monthly_hours, Length: 15002, dtype: int64

In [76]:
# 查看连续值分布
np.histogram(amh_s.values, bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [79]:
# 围栏方式  bins 左闭右开
np.histogram(amh_s.values, bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [80]:
# bins 左开右闭
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

In [81]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

###  time_spend_company 分析

In [82]:
tsc_s = df['time_spend_company']

In [84]:
tsc_s.value_counts().sort_index()

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

In [85]:
tsc_s.mean()

3.498066924410079

### Work_accident 分析

In [86]:
wa_s = df['Work_accident']

In [87]:
wa_s.value_counts()

0    12833
1     2169
Name: Work_accident, dtype: int64

In [88]:
# 事故率
wa_s.mean()

0.14458072257032395

### left 分析

In [89]:
l_s = df['left']

In [90]:
l_s.value_counts()

0    11428
1     3574
Name: left, dtype: int64

### promotion_last_5years 分析

In [91]:
pl5_s = df['promotion_last_5years']

In [92]:
pl5_s.value_counts()

0    14683
1      319
Name: promotion_last_5years, dtype: int64

### salary 分析

In [93]:
s_s = df['salary']

In [94]:
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

In [98]:
# 删除异常值
s_s = s_s.where(s_s!='nme').dropna()

In [99]:
s_s.value_counts()

low       7318
medium    6446
high      1237
Name: salary, dtype: int64

### department 分析

In [100]:
d_s = df['department']

In [102]:
d_s.value_counts(normalize=True)

sales          0.275963
technical      0.181309
support        0.148647
IT             0.081789
product_mng    0.060125
marketing      0.057192
RandD          0.052460
accounting     0.051127
hr             0.049260
management     0.041994
sale           0.000133
Name: department, dtype: float64

In [103]:
# 删除异常值
d_s =d_s.where(d_s!='sale').dropna()

In [104]:
d_s

0          sales
1          sales
2          sales
3          sales
4          sales
          ...   
14995    support
14996    support
14997    support
14998    support
14999    support
Name: department, Length: 15000, dtype: object

## 简单的对比分析

In [106]:
# 删除异常值 axis  0表示行  1表示列  all都为null删除  any只要有一个就删除 
df = df.dropna(axis=0, how='any')

In [107]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14995                    160                   3              0     1   
14996                    143                   3              0     1   
14997                    280                   4              0     1   
14998                    158                   3              0     1   
15001                    158                   2              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  
15001                      0       sale     nme  

[15000 rows x 10 columns]

In [108]:
# 进一步去除异常值
df = df[df['last_evaluation']<=1][df['salary']!='nme'][df['department']!='sale']

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


In [109]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1                        262                   6              0     1   
2                        272                   4              0     1   
3                        223                   5              0     1   
4                        159                   3              0     1   
...                      ...                 ...            ...   ...   
14994                    151                   3              0     1   
14995                    160                   3              0     1   
14996                    143                   3              0     1   
14997                    280                   4              0     1   
14998                    158                   3              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [110]:
# 以部门为单位进行简单的对比分析
# 以部门为单位分组，聚合方法使用均值
df.groupby('department').mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294

In [112]:
# 取出其中的几列进行对比分析
df.loc[:, ['last_evaluation', 'department']].groupby('department').mean()

last_evaluation
department                  
IT                  0.716830
RandD               0.712122
accounting          0.717718
hr                  0.708850
management          0.724000
marketing           0.715886
product_mng         0.714756
sales               0.709717
support             0.723109
technical           0.721099

In [113]:
# 自定义聚合函数进行分析 极差（最大值-最小值）
df.loc[:, ["average_monthly_hours", "department"]].groupby('department')['average_monthly_hours'].apply(lambda x:x.max()-x.min())

department
IT             212
RandD          210
accounting     213
hr             212
management     210
marketing      214
product_mng    212
sales          214
support        214
technical      213
Name: average_monthly_hours, dtype: int64