# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
# create from python list
list_1 = [1, 2, 3, 4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [8]:
list_2 = [5, 6, 7, 8]
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
array_2.shape

(2, 4)

In [10]:
array_2.size

8

In [11]:
array_2.dtype

dtype('int64')

##### 通过arange创建数组

In [13]:
array_4 = np.arange(1, 10, 2)
array_4

array([1, 3, 5, 7, 9])

##### 特殊函数创建特殊矩阵

In [14]:
# 全0矩阵
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### 访问数组中的元素

In [17]:
# 一维数组
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[1]

2

In [19]:
a[1:5]

array([2, 3, 4, 5])

In [20]:
# 二维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b[1][0]

4

In [22]:
b[1, 0]

4

In [23]:
# 切片
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c[:2, 1:]

array([[2, 3],
       [5, 6]])