# 快速创建数组

In [1]:
import numpy as np

In [2]:
# 创建一个随机正态分布的一维数组
np.random.randn(10)

array([ 1.15377718, -0.39914362,  0.01754117, -1.94394691, -0.81680615,
       -0.82723022, -0.97352603,  0.05058803, -0.01771289, -0.21014619])

In [3]:
# 返回10以内的一个随机数
np.random.randint(10)

3

In [4]:
# 创建一个2x3的矩阵
np.random.randint(10, size=(2, 3))

array([[5, 9, 1],
       [9, 8, 3]])

In [6]:
# 创建一个4x5的矩阵(由一维变化而来)
np.random.randint(10, size=20).reshape(4, 5)

array([[2, 6, 7, 9, 6],
       [4, 7, 7, 7, 7],
       [9, 3, 1, 9, 2],
       [7, 7, 0, 2, 6]])

# 数组的运算

In [7]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [8]:
b = np.random.randint(10, size=20).reshape(4, 5)

In [9]:
a

array([[4, 0, 3, 1, 9],
       [4, 9, 8, 7, 1],
       [5, 5, 1, 3, 4],
       [3, 1, 6, 0, 8]])

In [10]:
b

array([[1, 8, 3, 0, 3],
       [1, 8, 5, 5, 0],
       [9, 2, 5, 9, 6],
       [3, 6, 8, 1, 2]])

In [11]:
a+b

array([[ 5,  8,  6,  1, 12],
       [ 5, 17, 13, 12,  1],
       [14,  7,  6, 12, 10],
       [ 6,  7, 14,  1, 10]])

In [12]:
a-b

array([[ 3, -8,  0,  1,  6],
       [ 3,  1,  3,  2,  1],
       [-4,  3, -4, -6, -2],
       [ 0, -5, -2, -1,  6]])

In [13]:
a * b

array([[ 4,  0,  9,  0, 27],
       [ 4, 72, 40, 35,  0],
       [45, 10,  5, 27, 24],
       [ 9,  6, 48,  0, 16]])

In [14]:
a/b

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[4.        , 0.        , 1.        ,        inf, 3.        ],
       [4.        , 1.125     , 1.6       , 1.4       ,        inf],
       [0.55555556, 2.5       , 0.2       , 0.33333333, 0.66666667],
       [1.        , 0.16666667, 0.75      , 0.        , 4.        ]])

## 创建矩阵

In [15]:
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# 将a数组转换成矩阵
np.mat(a)

matrix([[4, 0, 3, 1, 9],
        [4, 9, 8, 7, 1],
        [5, 5, 1, 3, 4],
        [3, 1, 6, 0, 8]])

## 矩阵的运算

In [18]:
A = np.mat(a)

In [19]:
B = np.mat(b)

In [20]:
A 

matrix([[4, 0, 3, 1, 9],
        [4, 9, 8, 7, 1],
        [5, 5, 1, 3, 4],
        [3, 1, 6, 0, 8]])

In [21]:
B 

matrix([[1, 8, 3, 0, 3],
        [1, 8, 5, 5, 0],
        [9, 2, 5, 9, 6],
        [3, 6, 8, 1, 2]])

In [22]:
A + B

matrix([[ 5,  8,  6,  1, 12],
        [ 5, 17, 13, 12,  1],
        [14,  7,  6, 12, 10],
        [ 6,  7, 14,  1, 10]])

In [23]:
A - B

matrix([[ 3, -8,  0,  1,  6],
        [ 3,  1,  3,  2,  1],
        [-4,  3, -4, -6, -2],
        [ 0, -5, -2, -1,  6]])

In [25]:
C = np.mat(np.random.randint(10, size=20).reshape(4, 5))

In [26]:
D = np.mat(np.random.randint(10, size=20).reshape(5, 4))

In [27]:
C * D

matrix([[ 48,  53,  88,  93],
        [ 45,  47,  99,  79],
        [110, 147, 122,  99],
        [ 65, 102,  96,  70]])

# array 常用的函数

In [28]:
a = np.random.randint(10, size=20).reshape(4, 5)

In [29]:
# 返回数组中的唯一值
np.unique(a)

array([0, 1, 2, 3, 4, 5, 8, 9])

In [30]:
a

array([[1, 9, 4, 1, 4],
       [2, 3, 4, 9, 9],
       [2, 3, 1, 4, 5],
       [3, 2, 5, 8, 0]])

In [32]:
# 数组中每列的和
sum(a)

array([ 8, 17, 14, 22, 18])

In [34]:
# 求具体某一行的和
sum(a[0])

19

In [35]:
# 求具体某一列的和
sum(a[:, 0])

8

In [36]:
# 求数组中的最大值
a.max()

9

In [39]:
# 求具体某一行的最大值
max(a[2])

5

In [41]:
# 求具体某一列的最大值
max(a[:, 2])

5

# Array中的input和output

## 使用pickle序列化numpy array

In [42]:
import pickle
import numpy as np

In [43]:
x = np.arange(10)

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
f = open('x.pkl', 'wb')

In [46]:
# 将x写入f中
pickle.dump(x, f)

In [53]:
# 查看当前路径下的文件
!ls

Array操作.ipynb             travel_data.csv
python单例模型.ipynb        x.pkl
python算法实现.ipynb        数据分析案例.ipynb
state_tax_data.csv          数组与矩阵运算.ipynb
terrorist_attack_data.csv


In [59]:
# 读取x中的内容
f = open('x.pkl', 'rb')

In [60]:
pickle.load(f)

EOFError: Ran out of input

### 更方便的实现

In [61]:
# 保存
np.save('my_array', x)

In [62]:
!ls

Array操作.ipynb             terrorist_attack_data.csv
my_array.npy                travel_data.csv
python单例模型.ipynb        x.pkl
python算法实现.ipynb        数据分析案例.ipynb
state_tax_data.csv          数组与矩阵运算.ipynb


In [64]:
# 读取
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
y = np.arange(20)

In [66]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
# 存取多个数据
np.savez('two_array.npz', a=x, b=y)

In [68]:
!ls

Array操作.ipynb             travel_data.csv
my_array.npy                two_array.npz
python单例模型.ipynb        x.pkl
python算法实现.ipynb        数据分析案例.ipynb
state_tax_data.csv          数组与矩阵运算.ipynb
terrorist_attack_data.csv


In [69]:
# 读取
c = np.load('two_array.npz')

In [71]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])